# Removes the default index specified on default

run "rm public/index.html"

# Creates the Procfile necessary to boot the server

file "Procfile", <<-CODE
web: bundle exec rails server thin -p $PORT
CODE

# Add all the necessary basic gems to Gemfile

file "Gemfile", <<-GEMFILE, :force => true
source 'https://rubygems.org'

gem 'rails', '3.2.8'
gem 'jquery-rails'
gem 'pg'
gem 'slim'
gem 'thin'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'compass-rails'
  gem 'susy'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
GEMFILE

# Create example project file for Sublime Text 2.

file "example.sublime-project", <<-CODE
{
  "folders":
  [
    {
      "folder_exclude_patterns": ["db", "lib", "doc", "log", "tmp", "script", "test"],
      "file_exclude_patterns": ["config.ru", "Gemfile.lock", "Procfile", "Rakefile", "README.rdoc", ".gitkeep"]
    }
  ]
}
CODE

# Create .gitignore

file ".gitignore", <<-CODE, :force => true
# See http://help.github.com/ignore-files/ for more about ignoring files.
#
# If you find yourself ignoring temporary files generated by your text editor
# or operating system, you probably want to add a global ignore instead:
#   git config --global core.excludesfile ~/.gitignore_global

# Ignore bundler config
/.bundle

# Ignore the default SQLite database.
/db/*.sqlite3

# Ignore all logfiles and tempfiles.
/log/*.log
/tmp

# Read about how to use .gitignore: http://h5bp.com/ae

# Numerous always-ignore extensions
*.diff
*.err
*.orig
*.log
*.rej
*.swo
*.swp
*.vi
*~
*.sass-cache

# OS or Editor folders
.DS_Store
._*
Thumbs.db
.cache
.project
.settings
.tmproj
nbproject
*.sublime-project
*.sublime-workspace

# Dreamweaver added files
_notes
dwsync.xml

# Komodo
*.komodoproject
.komodotools

# Espresso
*.esproj
*.espressostorage

# Rubinius
*.rbc

# Folders to ignore
.hg
.svn
.CVS
intermediate
publish
.idea

# build script local files
build/buildinfo.properties
build/config/buildinfo.properties
CODE

# Download JavaScript libraries

inside('vendor/assets/javascripts') do
    run 'curl -s https://raw.github.com/dotjay/hashgrid/master/hashgrid.js > hashgrid.js'
    run 'curl -s https://raw.github.com/imsky/holder/master/holder.js > holder.js'
    run 'curl -s http://modernizr.com/downloads/modernizr.js > modernizr.js'
    run 'curl -s https://raw.github.com/keithclark/selectivizr/master/selectivizr.js > selectivizr.js'
  end

















